languageCode = "en-us"
title = "Seray Network Solutions"
theme = "crab"
baseurl = "https://Serayllc.github.io/"

[params]
description = "Your network is your castle, let us help you defend it!"
# logoimage = "/img/lock.jpg"
# copyright = "foo"

# mathjax = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
## Uncomment if you want mathjax enabled. The above cdn source is taken from https://gohugo.io/content-management/formats/#mathjax-with-hugo



[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

# [[menu.main]]
# weight = 1
# name = "Home"
# url = "/"

[[menu.main]]
weight = 1
name = "Services"
url = "/services/"

[[menu.main]]
weight = 2
name = "Blog"
url = "/blog/"

[[menu.main]]
weight = 3
name = "Contact"
url = "/contact/"
